on:
  fork:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
jobs:
  repo_forked:
    permissions: 
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: Mozzart88/test-action@main
        with:
         repo-token: ${{ secrets.GITHUB_TOKEN }}
