on:
  fork:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  repo_forked:
    runs-on: ubuntu-latest
    steps:
      - uses: Mozzart88/test-action@main
        with:
         repo-token: ${{ secrets.GITHUB_TOKEN }}
